Search.appendIndex(
    [
                {
            "fqsen": "\\MatthiasMullie\\Types\\AbstractType",
            "name": "AbstractType",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-AbstractType.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\AbstractType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-AbstractType.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\AbstractType\u003A\u003Atest\u0028\u0029",
            "name": "test",
            "summary": "Simply\u0020checks\u0020whether\u0020the\u0020value\u0020matches\u0020the\u0020type,\u0020without\u0020actually\nconverting\/casting\u0020it.",
            "url": "classes/MatthiasMullie-Types-AbstractType.html#method_test"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\AbstractType\u003A\u003AgetScalarValue\u0028\u0029",
            "name": "getScalarValue",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-AbstractType.html#method_getScalarValue"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\AbstractType\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-AbstractType.html#property_description"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Alphanumeric",
            "name": "Alphanumeric",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Alphanumeric.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Alphanumeric\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Alphanumeric.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Any",
            "name": "Any",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Any.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Any\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Any.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Boolean",
            "name": "Boolean",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Boolean.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Boolean\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Boolean.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Coordinate",
            "name": "Coordinate",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Coordinate.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Coordinate\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Coordinate.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Double",
            "name": "Double",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Double.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Double\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Double.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Email",
            "name": "Email",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Email.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Email\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Email.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Enum",
            "name": "Enum",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Enum.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Enum\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Enum.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Enum\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Enum.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Hexadecimal",
            "name": "Hexadecimal",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Hexadecimal.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Hexadecimal\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Hexadecimal.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Integer",
            "name": "Integer",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Integer.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Integer\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Integer.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-InvalidArgumentException.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Json",
            "name": "Json",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Json.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Json\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Json.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Json\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Json.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Map",
            "name": "Map",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Map.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Map\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Map.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Map\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Map.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Numeric",
            "name": "Numeric",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Numeric.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Numeric\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Numeric.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\OneOf",
            "name": "OneOf",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-OneOf.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\OneOf\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-OneOf.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\OneOf\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-OneOf.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Optional",
            "name": "Optional",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Optional.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Optional\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Optional.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Optional\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Optional.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\QueryString",
            "name": "QueryString",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-QueryString.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\QueryString\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-QueryString.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\QueryString\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-QueryString.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Sequence",
            "name": "Sequence",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Sequence.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Sequence\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Sequence.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Sequence\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Sequence.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Sha1",
            "name": "Sha1",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Sha1.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Sha1\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Sha1.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Sha512",
            "name": "Sha512",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Sha512.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Sha512\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Sha512.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Text",
            "name": "Text",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Text.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Text\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Text.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\TypeInterface",
            "name": "TypeInterface",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-TypeInterface.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\TypeInterface\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Invoke\u0020the\u0020type\u0020on\u0020given\u0020input\u003B\u0020converting\/casting\u0020it\u0020as\u0020possible,\nor\u0020throwing\u0020an\u0020exception\u0020upon\u0020failure.",
            "url": "classes/MatthiasMullie-Types-TypeInterface.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\TypeInterface\u003A\u003Atest\u0028\u0029",
            "name": "test",
            "summary": "Simply\u0020checks\u0020whether\u0020the\u0020value\u0020matches\u0020the\u0020type,\u0020without\u0020actually\nconverting\/casting\u0020it.",
            "url": "classes/MatthiasMullie-Types-TypeInterface.html#method_test"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Undefined",
            "name": "Undefined",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Undefined.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Undefined\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Undefined.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Url",
            "name": "Url",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Url.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\Url\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-Url.html#method___invoke"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\UrlEncoded",
            "name": "UrlEncoded",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-UrlEncoded.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\UrlEncoded\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-UrlEncoded.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Types\\UrlEncoded\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/MatthiasMullie-Types-UrlEncoded.html#method___invoke"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Types",
            "name": "Types",
            "summary": "",
            "url": "namespaces/matthiasmullie-types.html"
        },                {
            "fqsen": "\\MatthiasMullie",
            "name": "MatthiasMullie",
            "summary": "",
            "url": "namespaces/matthiasmullie.html"
        }            ]
);
